### ISSUE TITLE
可以查看任务执行之后的状态吗？

### ISSUE THREAD

**Issue by suiyang** [snower/forsun#2]
是否可以查看任务执行后的日志和任务是否正常完成

**Comment by snower** [comment]
forsun定时任务的管理和触发，触发之后执行的任务应该很简单，一般来说应该配合异步任务队列来使用，定时到期触发队列新任务推送，所以任务执行的结果和出错是否重试应该由异步队列来管理保存

一个服务应该只做一件事情
