### ISSUE TITLE
对redis设置过的requirepass不考虑吗？

### ISSUE THREAD

**Issue by Frewen** [snower/forsun#3]
对redis设置过的requirepass不考虑吗？
给定的redis驱动，redis参数并没有针对password进行设置的地方？如何解决？

`action redis 1529480220 {u'host': u'127.0.0.1', u'selected_db': u'0', u'command': u'RPUSH \'queues:default\' \'{\\"job\\":\\"Illuminate\\\\\\\\Events\\\\\\\\CallQueuedHandler@call\\",\\"data\\":{\\"class\\":\\"Snower\\\\\\\\LaravelForsun\\\\\\\\Jobs\\\\\\\\CommandRunHandler\\",\\"method\\":\\"handle\\",\\"data\\":\\"a:1:{i:0;s:70:\\\\\\"\\\'\\\\/usr\\\\/local\\\\/Cellar\\\\/php@7.1\\\\/7.1.17\\\\/bin\\\\/php\\\' artisan forsun:test --force\\\\\\";}\\"}}\'', u'port': u'6380'} execute error: NOAUTH Authentication required.`

**Comment by snower** [comment]
很少有人设置redis密码，所以忽略了，我来修改一下。

**Comment by snower** [comment]
已修改，你可以重新安装forsun 0.0.5版本和forsun-laravel 1.0.1版
感谢反馈！

**Comment by Frewen** [comment]
感谢修正

**Comment by Frewen** [comment]
snower/forsun-laravel 这个包似乎没有更新。composer 1.0.1版本里面 没有最新的代码，通过Releases 下载1.0.1zip包 也不是最新的代码，请检查谢谢

**Comment by snower** [comment]
好吧，有点不怎么会玩composer，没有提交新的tag，使用v1.0.2吧
