### ISSUE TITLE
你好。请问使用redis持久化存储启动，如何设置认证密码？

### ISSUE THREAD

**Issue by carrywin** [snower/forsun#4]
--driver-redis-password ?

**Comment by snower** [comment]
原来没想到真有人设置密码，没支持这个参数，现在已经添加，你可以安装新版本使用。

建议使用配置文件设置，具体设置参数可以看forsun.conf.example文件。

谢谢！

**Comment by carrywin** [comment]
> 原来没想到真有人设置密码，没支持这个参数，现在已经添加，你可以安装新版本使用。
> 
> 建议使用配置文件设置，具体设置参数可以看forsun.conf.example文件。
> 
> 谢谢！

Redis的安全性还是要考虑的。黑客喜欢扫描没设置密码的redis服务器进去搞事。哈哈。谢谢你的建议。Nice job!
